### ISSUE TITLE
api.sandbox.push.apple.com option

### ISSUE THREAD

**Issue by robaac** [dpikalov/push-apis#1]
How is it possible to change the url for apple notification, to include the sandbox environment.

**Comment by dpikalov** [comment]
> How is it possible to change the url for apple notification, to include the sandbox environment.

Added optional parameter "server" in v0.9.5.

```
const credentials = {
  server: "api.sandbox.push.apple.com",
  ...
}
await pushApi.sendMessageApple( credentials, token, payload  )

```

**Comment by dpikalov** [comment]
See reply to @robaac
